### PR TITLE
Fix unexpected lowercase route params

### LINKED ISSUE #6: Route params appear lowercased in the route string
Hi, thanks for this nice integration that reduces manual work for typed routes!

It appears that the routes are unexpectedly lowercased in the generated route string list.
This leads to a broken output because the declared type of the params used to build links are not lowercase, instead preserving the expected original names.

The root cause for this is that Astro itself lowercases the `route.pattern` field when building the route list, literally with a final `.toLowerCase()` call, apparently for deduplication purposes. This behaviour has been introduced in Astro [in this quite old commit](https://github.com/withastro/astro/commit/23fceb93ac14a34b3fabc3107922428e7de4b627), maybe it can be reconsidered over there but that might be a breaking change for other integrations.

### PR DESCRIPTION
**Pull request by joanrieu**
Closes #6

### CODE REVIEW

File: package/src/integration.ts [hunk 1]
```diff
@@ -22,8 +22,14 @@ function getDtsContent(
 		if (!(type === "page" || type === "endpoint")) {
 			continue;
 		}
-		const pattern = `${withoutTrailingSlash(base)}${route.pattern}`;
 		const segments = route.segments.flat();
+		const pattern = `${withoutTrailingSlash(base)}${segments
```
Comment (florian-lefebvre) [inline package/src/integration.ts]: Can you add a comment with the source of the original code?

**Review by florian-lefebvre — CHANGES_REQUESTED** [review]
This needs a patch changeset

File: package/src/integration.ts (hunk 1 above)
Comment (joanrieu) [reply package/src/integration.ts]: Sure thing! Added a short note with the reason for the change too.

**Comment by joanrieu** [comment]
MR updated :)

**Review by florian-lefebvre — APPROVED** [review]
Thank you!
